_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 71
                - 95
                - 103
            "2":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 71
                - 95
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.9
            "6": 4.51.0
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
bart_scorer_checkpoint:
    value: facebook/bart-large-cnn
baseline_score:
    value: 0.5
batch_size:
    value: 4
bert_scorer_batch_size:
    value: 1
bert_scorer_model_type:
    value: microsoft/deberta-xlarge-mnli
data_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/data/transformed
dataset_type:
    value: TimeTravel
delta_m1_enabled:
    value: false
dev_file:
    value: dev_data_sample.json
learning_rate:
    value: 2e-05
logs_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/logs
max_gen_length:
    value: 250
max_length:
    value: 512
model_name:
    value: google/flan-t5-large
models_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/models
num_workers:
    value: 3
objective_clipping:
    value: false
output_attentions:
    value: false
pg_checkpoint_path:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/models/model_2025-04-17-22/checkpoint-epoch=01-val_loss=0.80.ckpt
pg_epochs:
    value: 1
pg_experiment:
    value: delta_m1
pg_from_checkpoint:
    value: true
results_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/results
reward_metric:
    value: bart
root_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL
scorer_device:
    value: cuda:0
shuffle:
    value: true
temperature:
    value: 0.7
test_file:
    value: test_data_sample.json
train_file:
    value: train_supervised_small_sample.json
use_bart:
    value: true
use_bert:
    value: true
use_bleu:
    value: true
use_custom_loss:
    value: false
use_greedy_reward:
    value: false
