# /data/agirard/Projects/TimeTravel-PolicyGradientRL/src/pg/art/utils/metrics.py
import logging
#from sacrebleu.metrics import BLEU
from rouge import Rouge
#from bert_score import BERTScorer
import torch
from src.pg.art.utils.config_art import CONFIG
from src.BARTScore_metric.bart_score import BARTScorer

logger = logging.getLogger(__name__)


class MetricsEvaluator:
    """
    A class for evaluating text generation models using various metrics such as BLEU, ROUGE, BERTScore, and BARTScore.
    """

    def __init__(self):
        """
        Initializes the metric evaluators based on the configurations provided in CONFIG.
        """
        # print(f"Initializing MetricsEvaluator with config: {CONFIG}")

        # Initialize ROUGE for ROUGE score calculation
        self.rouge = Rouge()

        # Initialize BARTScorer if configured to use BARTScore
        self.bart_scorer = (
            BARTScorer(
                device=CONFIG.get("scorer_device", "cuda" if torch.cuda.is_available() else "cpu"),
                checkpoint=CONFIG.get("bart_scorer_checkpoint", "facebook/bart-large-cnn")
            ) if CONFIG.get("use_bart", False) else None
        )

        # print("MetricsEvaluator initialized.")

    def calculate_all_metrics(self, all_generated_texts, all_edited_endings, all_counterfactuals,
                              all_initials, all_premises):
        """
        Calculates metrics for all comparisons and aggregates them into a single dictionary.
        """
        all_metrics = {}

        comparisons = [
            ("prediction_edited", all_generated_texts, all_edited_endings),
            ("prediction_cf", all_generated_texts, all_counterfactuals),
            ("prediction_initial", all_generated_texts, all_initials),
            ("edited_ending_cf", all_edited_endings, all_counterfactuals),
            ("edited_ending_initial", all_edited_endings, all_initials),
        ]

        for label, texts_a, texts_b in comparisons:
            if texts_b:
                metrics = self.calculate_and_log_metrics(texts_a, texts_b, label)
                all_metrics.update(metrics)

        return all_metrics

    def calculate_and_log_metrics(self, generated_texts, references, comparison_label):
        """
        Calculate all similarity metrics for a single text comparison.
        """
        metrics = {}
        try:
            if self.bart_scorer:
                scores = self.bart_scorer.score(generated_texts, references, batch_size=4)
                avg_score = sum(scores) / len(scores) if scores else float('nan')
                metrics[f"{comparison_label}_bart_avg_score"] = avg_score
        except Exception as e:
            self._log_error(f"{comparison_label}_bart", e)
        try:
            rouge_scores = self.rouge.get_scores(generated_texts, references, avg=True)
            for rouge_type in ["rouge-1", "rouge-2", "rouge-l"]:
                metrics[f"{comparison_label}_{rouge_type}_f"] = rouge_scores[rouge_type]["f"]
        except Exception as e:
            self._log_error(f"{comparison_label}_rouge", e)

        return metrics

    def calculate_score(self, generated_texts, references):
        """
        Calculates the score based on the specified metric in CONFIG.


        Args:
            generated_texts (list of str): Texts generated by the model.
            references (list of str): Reference texts (ground truth).

        Returns:
            scores_tensor (torch.Tensor): A tensor of score values per example on the specified device.
        """
        score_metric = CONFIG.get("reward_metric", "rouge")
        scorer_device = CONFIG.get("scorer_device", "cpu")

        # Debugging prints for input and metric selection
        # print(f"Score metric: {score_metric}")
        # print(f"Generated texts: {generated_texts}")
        # print(f"Reference texts: {references}")

        # Ensure inputs are lists of strings
        generated_texts = [str(gt) for gt in generated_texts]
        references = [str(ref) for ref in references]

        # # For ROUGE, ensure no hypothesis is empty by replacing empty strings with a placeholder
        if score_metric == "rouge":
           generated_texts = [gt if gt.strip() != "" else " " for gt in generated_texts]

        # # Case 1: ROUGE-L is selected as the score metric
        if score_metric == "rouge":
            # print("Calculating ROUGE-L scores...")
            rouge_scores = self.rouge.get_scores(generated_texts, references, avg=False)
            scores = [score['rouge-l']['f'] for score in rouge_scores]  # Extract ROUGE-L F1 scores

        # Case 4: BARTScore is selected as the score metric
        elif score_metric == "bart":
            if self.bart_scorer is None:
                raise ValueError("BARTScore is not initialized. Set 'use_bart' to True in CONFIG.")
            # print("Calculating BARTScore...")
            scores = self.bart_scorer.score(generated_texts, references)  # BARTScore for each example

        # Unsupported score metric
        else:
            raise ValueError(f"Unsupported score metric: {score_metric}")

        # Convert scores to a tensor and move it to the specified device
        scores_tensor = torch.tensor(scores, dtype=torch.float32, device=scorer_device)
        # print(f"Scores tensor (on {scorer_device}): {scores_tensor}")  # Print the final scores tensor
        return scores_tensor

    def calculate_and_log_rouge_scores(self, all_generated_texts, all_edited_endings, all_counterfactuals, all_initials,
                                       all_premises, logger):
        """
        Calculates and logs ROUGE scores for various comparisons between generated texts and references.
        """
        # print("Calculating ROUGE scores...")

        all_comparisons = [
            ('rouge_prediction_edited', all_generated_texts, all_edited_endings),
            ('rouge_prediction_cf', all_generated_texts, all_counterfactuals),
            ('rouge_prediction_initial', all_generated_texts, all_initials),
            ('rouge_edited_ending_cf', all_edited_endings, all_counterfactuals),
            ('rouge_edited_ending_initial', all_edited_endings, all_initials),
        ]

        rouge_scores = {}
        for label, hypotheses, references in all_comparisons:
            if references:
                try:
                    rouge_scores_set = self.rouge.get_scores(hypotheses, references, avg=True)
                    score_type = 'rouge-l'
                    rouge_scores[f"{label}_{score_type}_f"] = rouge_scores_set[score_type]['f']
                    logger.info(f"{label}_{score_type}_f: {rouge_scores_set[score_type]['f']}")
                except Exception as e:
                    logger.error(f"Error calculating {label}: {e}")
                    rouge_scores[f"{label}_f"] = 'N/A'

        return rouge_scores
    
    def calculate_and_log_bart_similarity(self, all_generated_texts, all_edited_endings, all_counterfactuals,
                                          all_initials, all_premises, logger):
        """
        Calculates and logs BART-based similarity scores for a variety of text comparisons,
        using the BARTScorer to evaluate the similarity between different segments of texts.
        """
        print("Calculating BART similarity scores...")

        all_comparisons = [
            ('bart_prediction_edited', all_generated_texts, all_edited_endings),
            ('bart_prediction_cf', all_generated_texts, all_counterfactuals),
            ('bart_prediction_initial', all_generated_texts, all_initials),
            ('bart_edited_ending_cf', all_edited_endings, all_counterfactuals),
            ('bart_edited_ending_initial', all_edited_endings, all_initials),
        ]

        bart_scores = {}
        for label, src_texts, tgt_texts in all_comparisons:
            if tgt_texts:
                try:
                    scores = self.bart_scorer.score(src_texts, tgt_texts, batch_size=4)
                    avg_score = sum(scores) / len(scores) if scores else float('nan')
                    logger.info(f"{label}_avg_score: {avg_score}")
                    bart_scores[f"{label}_avg_score"] = avg_score
                    # print(f"{label}_avg_score: {avg_score}")
                except Exception as e:
                    logger.error(f"Error calculating {label}: {e}")
                    bart_scores[f"{label}_avg_score"] = 'N/A'
                    # print(f"Error calculating {label}: {e}")

        return bart_scores
