_wandb:
    value:
        cli_version: 0.18.3
        m:
            - "1": validation_overall_score
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": validation_pg_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": training_pg_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": training_pg_reward_mean_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": validation_pg_reward_mean
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 95
                - 103
            "2":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 95
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.8
            "5": 0.18.3
            "6": 4.37.2
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
bart_scorer_checkpoint:
    value: facebook/bart-large-cnn
baseline_score:
    value: 0.5
batch_size:
    value: 4
bert_scorer_batch_size:
    value: 4
bert_scorer_model_type:
    value: microsoft/deberta-xlarge-mnli
data_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/data/transformed
dev_file:
    value: dev_data_sample.json
file_label:
    value: _pg
learning_rate:
    value: 2e-05
logs_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/logs
max_gen_length:
    value: 250
max_length:
    value: 512
mle_checkpoint_path:
    value: null
mle_enabled:
    value: false
mle_epochs:
    value: 3
mle_from_checkpoint:
    value: false
model_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/models/pg_2024-11-25-16
model_name:
    value: google/flan-t5-base
models_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/models
num_workers:
    value: 3
output_attentions:
    value: false
pg_checkpoint_path:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/models/mle_2024-11-25-16/mle_checkpoint_epoch=epoch=2-val_loss=validation_mle_loss=12.17.ckpt
pg_enabled:
    value: true
pg_epochs:
    value: 3
pg_from_checkpoint:
    value: true
results_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL/results
reward_metric:
    value: bart
root_dir:
    value: /data/agirard/Projects/TimeTravel-PolicyGradientRL
scorer_device:
    value: cuda:0
shuffle:
    value: true
test_file:
    value: test_data_sample.json
train_file:
    value: train_supervised_small_sample.json
use_bart:
    value: true
use_bert:
    value: true
use_bleu:
    value: true
use_custom_loss:
    value: false
